export const IPC = {
  AUTH_OPEN_BROWSER: "auth:open-browser",
  AUTH_OPEN_IN_APP: "auth:open-in-app",
  AUTH_LOGOUT: "auth:logout",
  AUTH_GET_STATUS: "auth:get-status",
  AUTH_TOKEN_RECEIVED: "auth:token-received",
  AUTH_STATUS_CHANGED: "auth:status-changed",

  APP_GET_VERSION: "app:get-version",
  APP_PING_API: "app:ping-api",
  APP_OPEN_EXTERNAL: "app:open-external",
  APP_CLEAR_CACHE: "app:clear-cache",
  APP_EXPORT_LOG: "app:export-log",
  APP_GET_FORUM_WEB_URL: "app:get-forum-web-url",
  APP_PICK_DIRECTORY: "app:pick-directory",
  APP_OPEN_LZT_LINK: "app:open-lzt-link",
  APP_PICK_FILE: "app:pick-file",
  APP_READ_FILE: "app:read-file",

  SETTINGS_GET: "settings:get",
  SETTINGS_SET: "settings:set",
  SETTINGS_RESET: "settings:reset",
  SETTINGS_CHANGED: "settings:changed",
  ERROR_REPORT_SUBMIT: "error-report:submit",

  AUTOBUMP_GET: "autobump:get",
  AUTOBUMP_SET_GLOBAL: "autobump:set-global",
  AUTOBUMP_ADD_THREAD: "autobump:add-thread",
  AUTOBUMP_UPDATE_THREAD: "autobump:update-thread",
  AUTOBUMP_REMOVE_THREAD: "autobump:remove-thread",
  AUTOBUMP_BUMP_NOW: "autobump:bump-now",
  AUTOBUMP_CLEAR_LOG: "autobump:clear-log",
  AUTOBUMP_CHANGED: "autobump:changed",
  MARKET_AUTOBUMP_GET: "market-autobump:get",
  MARKET_AUTOBUMP_SET_GLOBAL: "market-autobump:set-global",
  MARKET_AUTOBUMP_RUN_NOW: "market-autobump:run-now",
  MARKET_AUTOBUMP_RESET_CYCLE: "market-autobump:reset-cycle",
  MARKET_AUTOBUMP_CLEAR_LOG: "market-autobump:clear-log",
  MARKET_AUTOBUMP_CHANGED: "market-autobump:changed",
  MARKET_AUTOBUMP_REFRESH_ITEMS: "market-autobump:refresh-items",
  MARKET_AUTOBUMP_BUMP_ITEM: "market-autobump:bump-item",

  AUTOREPRICE_GET: "autoreprice:get",
  AUTOREPRICE_SET_GLOBAL: "autoreprice:set-global",
  AUTOREPRICE_RUN_NOW: "autoreprice:run-now",
  AUTOREPRICE_CLEAR_LOG: "autoreprice:clear-log",
  AUTOREPRICE_CHANGED: "autoreprice:changed",

  PROFILE_SET_CURRENCY: "profile:set-currency",

  PROFILE_TOKEN_STATUS: "profile:token-status",
  PROFILE_TOKEN_SET: "profile:token-set",
  PROFILE_TOKEN_CLEAR: "profile:token-clear",
  PROFILE_GET_ME: "profile:get-me",
  PROFILE_GET_USER: "profile:get-user",
  PROFILE_GET_PERSONAL: "profile:get-personal",
  PROFILE_UPDATE_PERSONAL: "profile:update-personal",
  PROFILE_GET_CONTACT: "profile:get-contact",
  PROFILE_UPDATE_CONTACT: "profile:update-contact",
  PROFILE_GET_PREFERENCES: "profile:get-preferences",
  PROFILE_UPDATE_PREFERENCES: "profile:update-preferences",
  PROFILE_GET_PRIVACY: "profile:get-privacy",
  PROFILE_UPDATE_PRIVACY: "profile:update-privacy",
  PROFILE_NOTES_LIST: "profile:notes-list",
  PROFILE_NOTE_DELETE: "profile:note-delete",
  PROFILE_GET_FOLLOWERS: "profile:get-followers",
  PROFILE_GET_THREADS: "profile:get-threads",
  PROFILE_GET_THREAD: "profile:get-thread",
  PROFILE_GET_CLAIMS: "profile:get-claims",
  PROFILE_FOLLOW: "profile:follow",
  PROFILE_UNFOLLOW: "profile:unfollow",
  PROFILE_IGNORE: "profile:ignore",
  PROFILE_UNIGNORE: "profile:unignore",
  PROFILE_SEND_MESSAGE: "profile:send-message",
  PROFILE_NOTE_GET: "profile:note-get",
  PROFILE_NOTE_SET: "profile:note-set",
  PROFILE_GET_IGNORED: "profile:get-ignored",
  PROFILE_GET_NOTIFICATIONS: "profile:get-notifications",
  PROFILE_NOTIFICATIONS_READ: "profile:notifications-read",
  PROFILE_GET_CONVERSATIONS: "profile:get-conversations",
  PROFILE_GET_CONVERSATION_MESSAGES: "profile:get-conversation-messages",
  PROFILE_SEND_CONVERSATION_MESSAGE: "profile:send-conversation-message",
  PROFILE_SEARCH_USERS: "profile:search-users",
  PROFILE_SECRET_TYPES: "profile:secret-types",
  PROFILE_SECRET_SET: "profile:secret-set",
  PROFILE_SECRET_RESET: "profile:secret-reset",
  PROFILE_SECRET_RESET_CANCEL: "profile:secret-reset-cancel",

  PROFILE_GET_POSTS: "profile:get-posts",
  PROFILE_CREATE_POST: "profile:create-post",
  PROFILE_EDIT_POST: "profile:edit-post",
  PROFILE_DELETE_POST: "profile:delete-post",
  PROFILE_LIKE_POST: "profile:like-post",
  PROFILE_UNLIKE_POST: "profile:unlike-post",
  PROFILE_STICK_POST: "profile:stick-post",
  PROFILE_UNSTICK_POST: "profile:unstick-post",
  PROFILE_GET_POST_COMMENTS: "profile:get-post-comments",
  PROFILE_CREATE_POST_COMMENT: "profile:create-post-comment",
  PROFILE_EDIT_POST_COMMENT: "profile:edit-post-comment",
  PROFILE_DELETE_POST_COMMENT: "profile:delete-post-comment",
  PROFILE_GET_TROPHIES: "profile:get-trophies",

  MAIL_GET_LETTERS: "mail:get-letters",
  MASS_MAIL_START: "mass-mail:start",
  MASS_MAIL_STOP: "mass-mail:stop",
  MASS_MAIL_PROGRESS: "mass-mail:progress",

  PROXY_TEST: "proxy:test",
  PROXY_FETCH_MARKET: "proxy:fetch-market",

  PROXY_CHECK: "proxy:check",
  PROXY_CHECK_SITE: "proxy:check-site",
  IP_LOOKUP: "ip:lookup",

  MARKET_GET_ITEMS: "market:get-items",
  MARKET_GET_CATEGORIES: "market:get-categories",
  MARKET_GET_CATEGORY_PARAMS: "market:get-category-params",
  MARKET_GET_CATEGORY_GAMES: "market:get-category-games",
  MARKET_GET_USER_ITEMS: "market:get-user-items",
  MARKET_GET_USER_ITEM_STATES: "market:get-user-item-states",
  MARKET_GET_ACCOUNT: "market:get-account",
  MARKET_CHECK_ACCOUNT: "market:check-account",
  ACCOUNT_LOGIN: "account:login",
  ACCOUNT_LOGIN_CANCEL: "account:login-cancel",
  ACCOUNT_LOGIN_PROGRESS: "account:login-progress",
  MARKET_ITEM_NOTE_GET: "market:item-note-get",
  MARKET_ITEM_NOTE_SET: "market:item-note-set",
  MARKET_ITEM_NOTES_LIST: "market:item-notes-list",
  MARKET_ITEM_NOTE_DELETE: "market:item-note-delete",

  MARKET_TRANSFER: "market:transfer",
  MARKET_TRANSFER_FEE: "market:transfer-fee",
  MARKET_GET_CURRENCY: "market:get-currency",

  MARKET_GET_ORDERS: "market:get-orders",
  MARKET_GET_FAVOURITES: "market:get-favourites",
  MARKET_GET_VIEWED: "market:get-viewed",
  MARKET_GET_PAYMENTS: "market:get-payments",

  MARKET_GET_TAGS: "market:get-tags",
  MARKET_CREATE_TAG: "market:create-tag",
  MARKET_UPDATE_TAG: "market:update-tag",
  MARKET_DELETE_TAG: "market:delete-tag",
  MARKET_REORDER_TAGS: "market:reorder-tags",
  MARKET_ADD_ITEM_TAG: "market:add-item-tag",
  MARKET_REMOVE_ITEM_TAG: "market:remove-item-tag",
  MARKET_ADD_PUBLIC_TAG: "market:add-public-tag",
  MARKET_REMOVE_PUBLIC_TAG: "market:remove-public-tag",

  MARKET_STAR: "market:star",
  MARKET_UNSTAR: "market:unstar",

  MARKET_GET_TEMP_EMAIL_PASSWORD: "market:get-temp-email-password",
  MARKET_GET_MAFILE: "market:get-mafile",
  MARKET_GET_LETTERS: "market:get-letters",
  MARKET_GET_GUARD_CODE: "market:get-guard-code",

  MARKET_DOWNLOAD: "market:download",
  MARKET_ACCOUNTS_CACHE_GET: "market:accounts-cache-get",
  MARKET_ACCOUNTS_CACHE_SET: "market:accounts-cache-set",
  MARKET_ACCOUNTS_CACHE_CLEAR: "market:accounts-cache-clear",
  MARKET_PUBLISH_ITEM: "market:publish-item",
  MARKET_FAST_SELL: "market:fast-sell",
  MARKET_EDIT_PRICE: "market:edit-price",
  MARKET_RATE_LIMIT_STATE: "market:rate-limit-state",
  MARKET_GET_PROXIES: "market:get-proxies",
  MARKET_SELL_UPLOAD: "market:sell-upload",
  MARKET_PURCHASE_PREVIEW: "market:purchase-preview",
  MARKET_FAST_BUY: "market:fast-buy-account",
  MARKET_CART_LIST: "market:cart-list",
  MARKET_CART_ADD: "market:cart-add",
  MARKET_CART_REMOVE: "market:cart-remove",
  MARKET_CART_CLEAR: "market:cart-clear",

  CHECKER_STEAM: "checker:steam",

  CHAT_GET_ROOMS: "chat:get-rooms",
  CHAT_GET_MESSAGES: "chat:get-messages",
  CHAT_SEND_MESSAGE: "chat:send-message",
  CHAT_EDIT_MESSAGE: "chat:edit-message",
  CHAT_DELETE_MESSAGE: "chat:delete-message",
  CHAT_GET_ONLINE: "chat:get-online",
  CHAT_GET_LEADERBOARD: "chat:get-leaderboard",
  CHAT_GET_IGNORED: "chat:get-ignored",
  CHAT_IGNORE: "chat:ignore",
  CHAT_UNIGNORE: "chat:unignore",
  CHAT_GET_RULES: "chat:get-rules",
  CHAT_OPEN_WINDOW: "chat:open-window",
  FORUM_GET_TREE: "forum:get-tree",
  FORUM_GET_THREADS: "forum:get-threads",
  FORUM_GET_THREAD: "forum:get-thread",
  FORUM_GET_POSTS: "forum:get-posts",
  FORUM_CREATE_POST: "forum:create-post",
  FORUM_CREATE_THREAD: "forum:create-thread",
  FORUM_CREATE_CONTEST: "forum:create-contest",
  FORUM_GET_PREFIXES: "forum:get-prefixes",
  FORUM_GET_PREFIX_CSS: "forum:get-prefix-css",
  FORUM_GET_SECTION: "forum:get-section",
  FORUM_FOLLOW: "forum:follow",
  FORUM_UNFOLLOW: "forum:unfollow",
  FORUM_BOOKMARK: "forum:bookmark",
  FORUM_UNBOOKMARK: "forum:unbookmark",
  FORUM_LIKE_POST: "forum:like-post",
  FORUM_UNLIKE_POST: "forum:unlike-post",
  FORUM_HIDE_THREAD: "forum:hide-thread",
  FORUM_GET_COMMENTS: "forum:get-comments",
  FORUM_COMMENT_POST: "forum:comment-post",
  FORUM_GET_FEED_OPTIONS: "forum:get-feed-options",
  FORUM_SET_FEED_OPTIONS: "forum:set-feed-options",
  FORUM_WATCH_THREAD: "forum:watch-thread",
  FORUM_UNWATCH_THREAD: "forum:unwatch-thread",
  FORUM_EDIT_THREAD: "forum:edit-thread",
  FORUM_DELETE_THREAD: "forum:delete-thread",
  FORUM_BUMP_THREAD: "forum:bump-thread",
  FORUM_GET_MODERATOR_LOG: "forum:get-moderator-log",
  FORUM_GET_POST_BODY: "forum:get-post-body",
  FORUM_EDIT_POST: "forum:edit-post",
  FORUM_SEARCH_GIF: "forum:search-gif",

  PLUGINS_LIST: "plugins:list",
  PLUGINS_SAVE: "plugins:save",
  PLUGINS_DELETE: "plugins:delete",
  PLUGINS_TOGGLE: "plugins:toggle",

  TELEGRAM_TEST: "telegram:test",

  STREAMER_GET: "streamer:get",
  STREAMER_SET: "streamer:set",
  STREAMER_RESET: "streamer:reset",
  STREAMER_CHANGED: "streamer:changed",
  STREAMER_EXPORT: "streamer:export",
  STREAMER_IMPORT: "streamer:import",

  DISCORD_RPC_GET: "discord-rpc:get",
  DISCORD_RPC_SET: "discord-rpc:set",
  DISCORD_RPC_SET_ACTIVITY: "discord-rpc:set-activity",
  DISCORD_RPC_RECONNECT: "discord-rpc:reconnect",
  DISCORD_RPC_CHANGED: "discord-rpc:changed",

  HISTORY_QUERY: "history:query",
  HISTORY_GET_ENTRY: "history:get-entry",
  HISTORY_OBSERVE: "history:observe",
  HISTORY_RECORD_EDIT: "history:record-edit",
  HISTORY_DELETE_ENTRY: "history:delete-entry",
  HISTORY_CLEAR: "history:clear",
  HISTORY_MARKERS: "history:markers",
  HISTORY_CACHE_MEDIA: "history:cache-media",
  HISTORY_GET_MEDIA: "history:get-media",
  HISTORY_GET_USAGE: "history:get-usage",
  HISTORY_PURGE: "history:purge",
  HISTORY_CHANGED: "history:changed",

  ANALYSIS_GET_CONFIG: "analysis:get-config",
  ANALYSIS_GET_RULES: "analysis:get-rules",
  ANALYSIS_SAVE_KEY: "analysis:save-key",
  ANALYSIS_CLEAR_KEY: "analysis:clear-key",
  ANALYSIS_SET_ACTIVE: "analysis:set-active",
  ANALYSIS_SET_MODEL: "analysis:set-model",
  ANALYSIS_TEST: "analysis:test",
  ANALYSIS_ANALYZE: "analysis:analyze",
  ANALYSIS_GET_RESULTS: "analysis:get-results",
  ANALYSIS_SAVE_RESULTS: "analysis:save-results",
  ANALYSIS_CLEAR_RESULTS: "analysis:clear-results",

  UPDATE_CHECK: "update:check",
  UPDATE_DOWNLOAD: "update:download",
  UPDATE_INSTALL: "update:install",
  UPDATE_STATUS: "update:status",

  STORAGE_GET_USAGE: "storage:get-usage",
  STORAGE_CLEAR: "storage:clear",

  WINDOW_MINIMIZE: "window:minimize",
  WINDOW_TOGGLE_MAXIMIZE: "window:toggle-maximize",
  WINDOW_CLOSE: "window:close",
  WINDOW_IS_MAXIMIZED: "window:is-maximized",
  WINDOW_MAXIMIZE_CHANGED: "window:maximize-changed",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
